name: Swift CI

on:
  push:
    branches: [ "main", "develop", "feature-*" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # 🚨 Step 1: Detect unwanted files in the latest commit
    - name: Check for unwanted files
      run: |
        disallowed_files=$(git diff --name-only HEAD^ HEAD | grep -E '\.xcuserstate$|xcuserdata/|DerivedData/|ModuleCache.noindex/|\.DS_Store' || true)
        if [ -n "$disallowed_files" ]; then
          echo "❌ Found disallowed files in the last commit:"
          echo "$disallowed_files"
          exit 1
        fi

    # Step 2: Select correct Xcode version
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app

    # Step 3: Resolve dependencies (SPM)
    - name: Resolve Swift Packages
      run: xcodebuild -resolvePackageDependencies

    # Step 4: Build for iPhone 16 Pro (fallback iPhone 17)
    - name: Build for iPhone 16 Pro
      run: |
        xcodebuild -scheme brew \
        -sdk iphonesimulator \
        -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=latest' \
        build || \
        xcodebuild -scheme brew \
        -sdk iphonesimulator \
        -destination 'platform=iOS Simulator,name=iPhone 17,OS=latest' \
        build